# this is a configuration file for cruiseTrack2kml program

cruise = "AMAZOMIX"
ship = "ANTEA"
size_plots = 700
station_number = true
file = "netcdf"
time = 'TIME'
latitude = 'LATITUDE'
longitude = 'LONGITUDE'
profile = 'PROFILE'

# File is relative from Drive
[ctd]
file = 'data/amazomix/OS_AMAZOMIX_CTD.nc'
name = 'St'
name_format = 5
# prefix = 2
# skip = 1
# split = "PRFL,1,int,BEGIN_DATE,2,string,BEGIN_TIME,3,string,END_DATE,4,string,END_TIME,5,string,LAT,6,string,LAT_S,7,string,LON,8,string,LON_S,9,string,PMAX,10,float64,BOTTOM_DEPTH,11,float64"
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/CTD/AMAZOMIX-{:05d}_CTD.png"

[xbt]
#file = "none"
file = 'data/amazomix/OS_AMAZOMIX_XBT.nc'
name = 'Xbt'
name_format = 2
# prefix = 2
# skip = 2
# split = "PRFL,1,int,BEGIN_DATE,2,string,BEGIN_TIME,3,string,LAT,4,string,LAT_S,5,string,LON,6,string,LON_S,7,string,PMAX,8,float64,PROBE,9,string"
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/XBT/AMAZOMIX-{:05d}_XBT.png"

[tsg]
file = "data/amazomix/OS_AMAZOMIX_TSG.nc"
params = 'SSPS,SSTP'
# skip = 2
# split = "LATITUDE,2,float64,LONGITUDE,3,float64"
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/TSG/AMAZOMIX_TSG_COLCOR_SCATTER.png"

[windows]
drive = "m:"

[unix]
drive = "/m"
